In [2]:
import numpy as np

In [ ]:
a_list = [1,2,3]
b_list = [4,5,6]

print(a_list + b_list) # Regular list concatenation

[1, 2, 3, 4, 5, 6]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b) # numpy array addition, element-wise
print(a*b) # Element wise multiplication

[5 7 9]
[ 4 10 18]


In [ ]:
print(np.dot(a,b)) # multiplication + summation

32


In [ ]:
a_1 = np.array([[1,2,3],[4,5,6]])
b_1 = np.array([[1,2,3],[4,5,6]])

print(a_1.shape)
print(b_1.shape)

In [ ]:
print(a_1)
print(b_1.T) # Transpose of b_1, which will be 3x2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(2, 3)


In [7]:
np.dot(a_1, b_1.T) # a_1 is 2x3 and b_1.T is 3x2, so the result will be 2x2. Though b_1 is 2x3, we need to transpose it to make it compatible for multiplication with a_1

array([[14, 32],
       [32, 77]])

In [ ]:
a_1@b_1.T # This is the same as np.dot(a_1, b_1.T) but using the @ operator, which is a more concise way to perform matrix multiplication in Python.

array([[14, 32],
       [32, 77]])

In [ ]:
# apple, banana, smartphone, toy, furniture
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [25]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [23]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [26]:
sales = np.dot(shop_sold_amazon, price_amazon.T)

In [28]:
sales

# [[state_1(price_of_state_1), state_1(price_of_state_2)]
# [state_2(price_of_state_1), state_2(price_of_state_2)]]

array([[26300, 29230],
       [52600, 58460]])

In [33]:
diag = np.eye(2)
print(diag)

[[1. 0.]
 [0. 1.]]


In [34]:
np.sum(sales*diag)

np.float64(84760.0)

# Aggregation function

In [35]:
a_2 = np.array([1,2,3,4,5])

In [36]:
np.sum(a_2)

np.int64(15)

In [37]:
np.min(a_2)

np.int64(1)

In [ ]:
np.max(a_2)

np.int64(5)

In [ ]:
# [1,2,3,4,5]
a_3 = [1,2,100, 45, 450, 2, 5]
np.argmax(a_3) # index of the max element in the array
# np.argmin(a_3) # index of the min element in the array

np.int64(0)

In [10]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220], # state-2-price,
])

In [11]:
np.sum(price_amazon)

np.int64(2627)

In [12]:
np.sum(price_amazon, axis=0)
# axis->0 means sum over rows, keep columns

array([  64,   22, 2100,   21,  420])

In [13]:
np.sum(price_amazon, axis=1)
# axis->1 means sum over columns, keep rows

array([1250, 1377])

In [ ]:
np.mean(a_3) # mean is the average of the elements in the array

np.float64(86.42857142857143)

In [47]:
np.mean(price_amazon)

np.float64(262.7)

In [ ]:
np.mean(price_amazon, axis=1)

array([250. , 275.4])

In [ ]:
np.std(price_amazon, axis=1) # standard deviation is a measure of how spread out the numbers are in the array. 
# A low standard deviation means that the numbers are close to the mean, while a high standard deviation means that the numbers are more spread out. 
# In this case, state-1 has a higher standard deviation than state-2, which means that the prices in state-1 are more spread out than the prices in state-2.

array([381.73289091, 419.66539052, 419.66539052])

In [ ]:
np.var(price_amazon, axis=1) # variance is the square of the standard deviation, and it also measures how spread out the numbers are in the array.

array([145720.  , 176119.04, 176119.04])

In [ ]:
np.cumsum([1,2,4,5,6,100]) # cumulative sum, it returns an array where each element is the sum of all the previous elements in the original array.

array([  1,   3,   7,  12,  18, 118])

In [ ]:
np.median(price_amazon, axis=1) # median is the middle value of the sorted array. If the number of elements is even, then the median is the average of the two middle values.

array([30., 34., 34.])

In [60]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0


# sort, search, counting functions

In [6]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [7]:
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
# Instead of returning the sorted values themselves, 
# it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]


In [ ]:
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4)) # searchsorted returns the index where the value 4 would be inserted to maintain the sorted order of the array.
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr)) # returns the count of each non-negative integer in the array. The index of the returned array corresponds to the integer, and the value at that index corresponds to the count of that integer in the original array.

# 0,1,2,3,4,5,6,7,8
# 0,4,1....

Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [3]:
arr_new = np.array([3, 6, 1, 1, 1, 1, 1.2, 8, 2, 5, 6])

In [ ]:
print("Count of each element:", np.bincount(arr_new), rul) # bincount only works with non-negative integers, so it will throw an error when we try to use it with arr_new which contains a float (1.2).

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [74]:
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)

1
2
3
4


In [75]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [77]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(8)
# 2,4
# 1,8
# 2,2,2
# 2,6 (BEST)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
arr = np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.ndim # attibute of the class

3

In [83]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for x in np.nditer(arr): # nditer is a multi-dimensional iterator object to iterate over arrays of any shape. It provides a way to iterate over the elements of an array in a specific order, such as row-major or column-major order.
    print(x)

0
1
2
3
4
5
6
7


In [86]:
a = np.array([1, 2, 3])

In [87]:
b = a # 

In [88]:
print(id(a))
print(id(b))

2116798518768
2116798518768


In [89]:
b[0] = 100

In [90]:
print(a)

[100   2   3]


In [ ]:
b = a.copy() # copy creates a new array object with its own data. So, if we modify the copy, it will not modify the original array.

In [92]:
print(id(a))
print(id(b))

2116798518768
2117406015184


In [ ]:
a = np.array([1, 2, 3,])

b = a.view() # view creates a new array object that looks at the same data. So, if we modify the view, it will modify the original array as well.



In [95]:
print(id(a))
print(id(b))

2117413010000
2117413010480


In [ ]:
print(np.shares_memory(a, b)) # This function checks if two arrays share the same memory.

True


In [97]:
# vstack

a = np.array([[1,2]])
b = np.array([[3,4]])

In [ ]:
print(np.vstack((a,b))) # vertical stack, it will concatenate the arrays vertically (row-wise) instead of horizontally (column-wise).

[[1 2]
 [3 4]]


In [ ]:
print(np.hstack((a,b))) # horizontal stack, it will concatenate the arrays horizontally (column-wise) instead of vertically (row-wise).

[[1 2 3 4]]


# numpy char and strings

In [100]:
# np.char.<function_name>()

In [102]:
# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [105]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [106]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [107]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [130]:
def password(value):
    # print(value[-4:])
    p = np.array([value[-4:]])
    print(p)
    print(np.char.center(p, 30, fillchar='*'))

In [131]:
password("canwedoitlaterpass")

['pass']
['*************pass*************']


In [132]:
# np.char.replace()
a = np.array(['data_science', 'machine_learning'])

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [133]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()
print(np.char.find(a, 'learn')) 
# ['data_science', 'machine_learning']

[-1  8]


In [135]:
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[2 2]
[1 0]


# NUMPY COMPLETED